services:
  auth-database:
    image: postgres:16
    container_name: auth-database

    environment:
      POSTGRES_DB: ${DATASOURCE_NAME}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - auth-db-data:/var/lib/postgresql/data

  auth-service:
    image: thaua1/rota-facil-auth-service:latest

    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      DB_HOST: ${DB_HOST}

volumes:
  auth-db-data: