spring.application.name=auth-service
server.servlet.context-path=/auth
server.port=8084

# DATABASE
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_database}
spring.datasource.username=${DATASOURCE_USERNAME:rota-facil}
spring.datasource.password=${DATASOURCE_PASSWORD:admin}


#  EUREKA
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8081/eureka}
eureka.client.fetch-registry=true