spring.application.name=auth-service
server.servlet.context-path=/auth
server.port=8084


spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:5432/auth_database}
spring.datasource.username=${DATASOURCE_USERNAME:rota-facil}
spring.datasource.password=${DATASOURCE_PASSWORD:admin}